## Multidimensional arrays with numpy

In this example we'll introduce the numpy array system. This is a very powerful and fast extension of basic Python lists, for handling of large, multidimensional, numerical data of the sort that physicists use all the time.

Numpy is automatically loaded as part of our usual `import pylab as pl` module import, but for this exercise let's be more explicit and load numpy by itself (this is what happens *inside* pylab):

In [3]:
import numpy as np

### Creating arrays and matrices

Now let's create a 2D array, by passing a Python list-of-lists to the `np.array` constructor function:

In [4]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

This is a 2x3 matrix, so presumably we can do matrixy things with it, like transposing?

In [9]:
print(a.T)
a.T.shape

[[1 4]
 [2 5]
 [3 6]]


(3, 2)

Yes, that gave us a 3x2 as expected. And multiplying by a scalar?

In [5]:
5 * a

array([[ 5, 10, 15],
       [20, 25, 30]])

Hurrah!

### Matrix multiplication

Ok, let's make another matrix (this time using the `np.ones` function, which makes a matrix full of 1 values, with the given shape), and multiply them together:

In [11]:
b = 2 * np.ones([2,3])
print(b)
a * b.T

[[ 2.  2.  2.]
 [ 2.  2.  2.]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

What happened?! I tried to multiply a 2x3 matrix with a 3x2 matrix: that should have worked, right?

An important thing to be aware of is that numpy's default multiply operator is element-wise, not linear-algebra multiplication. So this is complaining because element-wise multiplication fails if the two arrays are not the same shape. If you want to do "normal" matrix multiplication, you need to use the numpy `matmul` function.

Let's see how matrix addition, element-wise multiplication, and linear-algebra multiplication work with our arrays: 

In [19]:
print(a + b)
print(a * b)
print(np.matmul(a,b.T))

[[ 3.  4.  5.]
 [ 6.  7.  8.]]
[[  2.   4.   6.]
 [  8.  10.  12.]]
[[ 12.  12.]
 [ 30.  30.]]


### Indexing and slicing

Now for a very powerful numpy feature: *selection and slicing* of arrays. This may be familiar to you from simple Python lists, but numpy can handle arrays of any dimensionality and allows you to both select elements along each dimension, and to reduce the dimension.

Let's make a 3D array for this, filled with random values:

In [21]:
c = np.random.rand(3,3,3)
print(c)

[[[ 0.55883962  0.27399886  0.13089367]
  [ 0.62924377  0.79254366  0.44239827]
  [ 0.29282705  0.7963434   0.21239824]]

 [[ 0.56872608  0.73532074  0.07852019]
  [ 0.24003302  0.87482845  0.584218  ]
  [ 0.40533184  0.74168804  0.51498622]]

 [[ 0.54552254  0.10854666  0.62715629]
  [ 0.29741373  0.97290016  0.21471381]
  [ 0.21375278  0.73402014  0.48545872]]]


If you look closely, you'll see that there are three sets of outer square brackets, and that this looks like three stacked 2D matrices: so this is a 3D array.

First, let's just pick out the 1D array for which the first and third dimension indices are 0:

In [22]:
c[0,:,0]

array([ 0.55883962,  0.62924377,  0.29282705])

Here, the square brackets are used for indexing as with simply Python arrays, but the indexing can be multidimensional with each dimension's indexing separated by a comma. The `:` without index numbers around it means "select all elements in this direction", which is much more convenient than writing `0:-1`.

Note that here numpy has automatically reshaped the array to be one-dimensional, since our slicing reduced the first and third dimensions to only having one index each.

Now, how about I allow the dimension indices to be 0 or 1 in the third dimension?

In [24]:
d = c[0,:,0:2]
print(d)

[[ 0.55883962  0.27399886]
 [ 0.62924377  0.79254366]
 [ 0.29282705  0.7963434 ]]


Cool. Numpy has now worked out that this is a 2D array (with two indices in the third dimension), and has reshaped accordingly.

### Logical indexing

Time for one last demo in this short tutorial: logical indexing. You can use logical operations to identify and select elements:

In [28]:
print(d > 0.5)
print(d[d > 0.5])

[[ True False]
 [ True  True]
 [False  True]]
[ 0.55883962  0.62924377  0.79254366  0.7963434 ]


Thanks for following this brief introduction to numpy array basics. You should now be able to create (multidimensional) arrays and manipulate them, which is the core skill of both data processing and linear algebra.

Of course there is much more to numpy, not least a large library of functions that can operate on arrays for computing statistics, linear algebra, curve-fitting, optimisation, Fourier transforms, and much more. You will find documentation at the numpy website, e.g. https://docs.scipy.org/doc/numpy/reference/index.html . And there is even more, higher-level scientific functionality in the partner SciPy library.